version: "3.8"

services:
  itmo-agent:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: itmo-bot
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      - ./app/config.yaml:/app/config.yaml
      - ./logs:/app/logs

    # Если нужно GPU
    # runtime: nvidia
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]